### ISSUE TITLE
No link to CI job in Slack notification

### ISSUE THREAD

**Issue by scottserok** [RenoFi/vidar#16]
It would be nice if there was also a link to the CI build job in both the failure and success Slack notifications. In the case of a failure, the CI job often has good context. In the case of a success, sometimes a job may have information or a manual step that others could more easily access if there's a link to the job.

CircleCI has an environment variable `CIRCLE_BUILD_URL`
TravisCI has an environment variable `TRAVIS_BUILD_WEB_URL`

We might somehow make the `vidar.yml` configurable to specify an environment variable for this, and only show the link in the Slack notification if defined/present.

**Comment by knapo** [comment]
Good idea!
